#!/bin/bash

export EC2_HOME=/usr/local/ec2/ec2-api-tools-1.7.2.1
export PATH=$PATH:$EC2_HOME/bin
export AWS_ACCESS_KEY=AKIAJXER5S7OHT6IGNNQ
export AWS_SECRET_KEY=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
export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY
export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_KEY
